/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Grafics.Menus;

/**
 *
 * @author Antonio Alvarez
 */
public class MenuCursos extends javax.swing.JFrame {

    /**
     * Creates new form MenuUsuarios
     */
    public MenuCursos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jToggleButtonListarCursos = new javax.swing.JToggleButton();
        jToggleButtonBuscarCursos = new javax.swing.JToggleButton();
        jToggleButtonAgregarCursos = new javax.swing.JToggleButton();
        jToggleButtonModificarCursos = new javax.swing.JToggleButton();
        jToggleButtonEliminarCursos = new javax.swing.JToggleButton();
        jToggleButtonCerrarCuso = new javax.swing.JToggleButton();
        jToggleButtonAtrás = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabelTitulo.setText("Menu Cursos");

        jToggleButtonListarCursos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButtonListarCursos.setText("Listar Cursos");
        jToggleButtonListarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonListarCursosActionPerformed(evt);
            }
        });

        jToggleButtonBuscarCursos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButtonBuscarCursos.setText("Buscar Curso");
        jToggleButtonBuscarCursos.setToolTipText("");
        jToggleButtonBuscarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonBuscarCursosActionPerformed(evt);
            }
        });

        jToggleButtonAgregarCursos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButtonAgregarCursos.setText("Agregar Curso");
        jToggleButtonAgregarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAgregarCursosActionPerformed(evt);
            }
        });

        jToggleButtonModificarCursos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButtonModificarCursos.setText("Modificar Curso");
        jToggleButtonModificarCursos.setToolTipText("");
        jToggleButtonModificarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonModificarCursosActionPerformed(evt);
            }
        });

        jToggleButtonEliminarCursos.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButtonEliminarCursos.setText("Eliminar Curso");
        jToggleButtonEliminarCursos.setActionCommand("Eliminar Curso");
        jToggleButtonEliminarCursos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonEliminarCursosActionPerformed(evt);
            }
        });

        jToggleButtonCerrarCuso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButtonCerrarCuso.setText("Cerrar Curso");
        jToggleButtonCerrarCuso.setToolTipText("");
        jToggleButtonCerrarCuso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCerrarCusoActionPerformed(evt);
            }
        });

        jToggleButtonAtrás.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jToggleButtonAtrás.setText("Atrás");
        jToggleButtonAtrás.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonAtrásActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitulo)
                .addGap(104, 104, 104))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButtonCerrarCuso, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonAtrás, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonListarCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonEliminarCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonBuscarCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonAgregarCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonModificarCursos, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelTitulo)
                .addGap(31, 31, 31)
                .addComponent(jToggleButtonListarCursos)
                .addGap(18, 18, 18)
                .addComponent(jToggleButtonBuscarCursos)
                .addGap(18, 18, 18)
                .addComponent(jToggleButtonAgregarCursos)
                .addGap(18, 18, 18)
                .addComponent(jToggleButtonModificarCursos)
                .addGap(18, 18, 18)
                .addComponent(jToggleButtonEliminarCursos)
                .addGap(18, 18, 18)
                .addComponent(jToggleButtonCerrarCuso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jToggleButtonAtrás)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonListarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonListarCursosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonListarCursosActionPerformed

    private void jToggleButtonBuscarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonBuscarCursosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonBuscarCursosActionPerformed

    private void jToggleButtonAgregarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAgregarCursosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonAgregarCursosActionPerformed

    private void jToggleButtonModificarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonModificarCursosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonModificarCursosActionPerformed

    private void jToggleButtonEliminarCursosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonEliminarCursosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonEliminarCursosActionPerformed

    private void jToggleButtonAtrásActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonAtrásActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonAtrásActionPerformed

    private void jToggleButtonCerrarCusoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCerrarCusoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonCerrarCusoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCursos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButtonAgregarCursos;
    private javax.swing.JToggleButton jToggleButtonAtrás;
    private javax.swing.JToggleButton jToggleButtonBuscarCursos;
    private javax.swing.JToggleButton jToggleButtonCerrarCuso;
    private javax.swing.JToggleButton jToggleButtonEliminarCursos;
    private javax.swing.JToggleButton jToggleButtonListarCursos;
    private javax.swing.JToggleButton jToggleButtonModificarCursos;
    // End of variables declaration//GEN-END:variables
}
